### ISSUE TITLE
🤗 [Question]: stripe return parameter_invalid_empty

### ISSUE THREAD

**Issue by jiaotiliu** [shurco/litecart#30]
### Question Description
**Ver.0.1.3**
stripe 400 Error

"description": "", is empty,but I had add the description
ITS WORK IN VER 0.1.2
### Code Snippet (optional)

```go
parameter_invalid_empty - line_items[0][price_data][product_data][description]
You passed an empty string for 'line_items[0][price_data][product_data][description]'. We assume empty values are an attempt to unset a parameter; however 'line_items[0][price_data][product_data][description]' cannot be unset. You should remove 'line_items[0][price_data][product_data][description]' from your request or supply a non-empty value.
```

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by shurco** [comment]
The structure of the website has been changed, and some scripts have been rewritten. Most likely, it is necessary to regenerate the site folder. You can simply delete this folder and restart the server, it will be created automatically.

Also, after the update, migration needs to be done since the database structure has been changed `litecart migrate`. Make a backup of the database beforehand.

**Comment by shurco** [comment]
@jiaotiliu update please for [v0.1.4](https://github.com/shurco/litecart/releases/tag/v0.1.4)
I managed to reproduce this error and fix it.
